<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            ["id"=>1,'paterno'=>" ", 'materno'=>" ", 'nombres'=>"Administrador", 'licencia'=>" ", 'genero'=>"M", 'carnet'=>" ", 'fechanac'=>"2000-01-01", 'email'=>"admin@test.com", 'password'=>Hash::make("admin"),"tipo"=>"ADMINISTRADOR"],
            ["id"=>2,'paterno'=>"ABASTO", 'materno'=>"PEREIRA", 'nombres'=>"SERAFÍN EDUARDO", 'licencia'=>"Or-6-036", 'genero'=>"M", 'carnet'=>"3558672", 'fechanac'=>"1978-3-23", 'email'=>"serafinabasto@masteroruro.cf", 'password'=>Hash::make("3558672Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>3,'paterno'=>"AGUILAR", 'materno'=>"LÓPEZ", 'nombres'=>"GONZALO ", 'licencia'=>"Or-6-069", 'genero'=>"M", 'carnet'=>"3098312", 'fechanac'=>"1964-7-17", 'email'=>"gonzaloaguilar@masteroruro.cf", 'password'=>Hash::make("3098312Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>4,'paterno'=>"ALÁ", 'materno'=>"MIRANDA", 'nombres'=>"EDWIN GUSTAVO", 'licencia'=>"Or-6-041", 'genero'=>"M", 'carnet'=>"3041219", 'fechanac'=>"1962-5-1", 'email'=>"edwinala@masteroruro.cf", 'password'=>Hash::make("3041219Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>5,'paterno'=>"ALÁ", 'materno'=>"MIRANDA", 'nombres'=>"HÉCTOR GREGORIO", 'licencia'=>"Or-6-001", 'genero'=>"M", 'carnet'=>"2729016", 'fechanac'=>"1951-11-28", 'email'=>"gregorioala@masteroruro.cf", 'password'=>Hash::make("2729016Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>6,'paterno'=>"ALÁ", 'materno'=>"MIRANDA", 'nombres'=>"PAZ GASTÓN", 'licencia'=>"Or-6-002", 'genero'=>"M", 'carnet'=>"2785003", 'fechanac'=>"1956-1-24", 'email'=>"pazala@masteroruro.cf", 'password'=>Hash::make("2785003Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>7,'paterno'=>"ALÁ", 'materno'=>"ROJAS", 'nombres'=>"HÉCTOR ARMANDO", 'licencia'=>"Or-6-043", 'genero'=>"M", 'carnet'=>"4074097", 'fechanac'=>"1983-10-7", 'email'=>"armandoala@masteroruro.cf", 'password'=>Hash::make("4074097Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>8,'paterno'=>"ANDRADE", 'materno'=>"ZEBALLOS", 'nombres'=>"MARÍA ANGÉLICA", 'licencia'=>"------", 'genero'=>"F", 'carnet'=>"4065469", 'fechanac'=>"1982-5-6", 'email'=>"mariaandrade@masteroruro.cf", 'password'=>Hash::make("4065469Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>9,'paterno'=>"ANGULO", 'materno'=>"ADUVIRI", 'nombres'=>"JOEL ", 'licencia'=>"Or-6-032", 'genero'=>"M", 'carnet'=>"5060052", 'fechanac'=>"1985-6-17", 'email'=>"joelangulo@masteroruro.cf", 'password'=>Hash::make("5060052Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>10,'paterno'=>"ANGULO", 'materno'=>"ADUVIRI", 'nombres'=>"JUAN GABRIEL", 'licencia'=>"Or-6-003", 'genero'=>"M", 'carnet'=>"7280470", 'fechanac'=>"1989-3-26", 'email'=>"juanangulo@masteroruro.cf", 'password'=>Hash::make("7280470Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>11,'paterno'=>"ANGULO", 'materno'=>"ALMARAZ", 'nombres'=>"ALVARO JAVIER", 'licencia'=>"Or-6-004", 'genero'=>"M", 'carnet'=>"952243", 'fechanac'=>"1959-6-1", 'email'=>"alvaroangulo@masteroruro.cf", 'password'=>Hash::make("952243Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>12,'paterno'=>"BAPTISTA", 'materno'=>"CHAPARRO", 'nombres'=>"JHONNY JULIO", 'licencia'=>"Or-6-061", 'genero'=>"M", 'carnet'=>"7307343", 'fechanac'=>"1991-8-27", 'email'=>"jhonnybaptista@masteroruro.cf", 'password'=>Hash::make("7307343Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>13,'paterno'=>"CALIZAYA", 'materno'=>"FLORES", 'nombres'=>"RUTH MARLEN", 'licencia'=>"Or-6-033", 'genero'=>"F", 'carnet'=>"3549419", 'fechanac'=>"1979-10-24", 'email'=>"ruthcalizaya@masteroruro.cf", 'password'=>Hash::make("3549419Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>14,'paterno'=>"CALLAHUARA", 'materno'=>"BUSTOS", 'nombres'=>"ARMINDA ", 'licencia'=>"Or-6-038", 'genero'=>"F", 'carnet'=>"2757664", 'fechanac'=>"1958-3-15", 'email'=>"armindacallahuara@masteroruro.cf", 'password'=>Hash::make("2757664Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>15,'paterno'=>"CANCHARI", 'materno'=>"YUCRA", 'nombres'=>"RICHARD JONAS", 'licencia'=>"Or-6-046", 'genero'=>"M", 'carnet'=>"506467", 'fechanac'=>"1981-3-29", 'email'=>"richardcanchari@masteroruro.cf", 'password'=>Hash::make("506467Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>16,'paterno'=>"CASTRO", 'materno'=>"ARCE", 'nombres'=>"ANA MARÍA", 'licencia'=>"Or-6-060", 'genero'=>"F", 'carnet'=>"2767936", 'fechanac'=>"1959-9-17", 'email'=>"anacastro@masteroruro.cf", 'password'=>Hash::make("2767936Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>17,'paterno'=>"CAYOJA", 'materno'=>"ALMENDRAS", 'nombres'=>"CARLOS ALBERTO", 'licencia'=>"Or-6-065", 'genero'=>"M", 'carnet'=>"5748457", 'fechanac'=>"1989-8-2", 'email'=>"carloscayoja@masteroruro.cf", 'password'=>Hash::make("5748457Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>18,'paterno'=>"CERROGRANDE", 'materno'=>"MARTÍNEZ", 'nombres'=>"JAMMY ", 'licencia'=>"Or-6-066", 'genero'=>"F", 'carnet'=>"7277236", 'fechanac'=>"1989-4-8", 'email'=>"jammycerrogrande@masteroruro.cf", 'password'=>Hash::make("7277236Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>19,'paterno'=>"CHAPARRO", 'materno'=>"CRUZ", 'nombres'=>"PORFIRIA ", 'licencia'=>"Or-6-062", 'genero'=>"F", 'carnet'=>"3507199", 'fechanac'=>"1970-9-15", 'email'=>"porfiriachaparro@masteroruro.cf", 'password'=>Hash::make("3507199Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>20,'paterno'=>"CHINO", 'materno'=>"COLQUE", 'nombres'=>"JHENNY PAMELA", 'licencia'=>"Or-6-005", 'genero'=>"F", 'carnet'=>"5067096", 'fechanac'=>"1982-1-8", 'email'=>"jhennychino@masteroruro.cf", 'password'=>Hash::make("5067096Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>21,'paterno'=>"CHOQUE", 'materno'=>"FERNÁNDEZ", 'nombres'=>"DAVID ", 'licencia'=>"Or-6-006", 'genero'=>"M", 'carnet'=>"5720901", 'fechanac'=>"1952-10-6", 'email'=>"davidchoque@masteroruro.cf", 'password'=>Hash::make("5720901Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>22,'paterno'=>"CHOQUE", 'materno'=>"FERNÁNDEZ", 'nombres'=>"ISABEL ERNESTINA", 'licencia'=>"Or-6-042", 'genero'=>"F", 'carnet'=>"4059836", 'fechanac'=>"1978-12-5", 'email'=>"isabelchoque@masteroruro.cf", 'password'=>Hash::make("4059836Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>23,'paterno'=>"CHOQUE", 'materno'=>"GARCÍA", 'nombres'=>"CÉSAR ", 'licencia'=>"Or-6-007", 'genero'=>"M", 'carnet'=>"676499", 'fechanac'=>"1956-6-4", 'email'=>"cesarchoque@masteroruro.cf", 'password'=>Hash::make("676499Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>24,'paterno'=>"CHOQUE", 'materno'=>"VINCENTI", 'nombres'=>"EUGENIO ", 'licencia'=>"Or-6-037", 'genero'=>"M", 'carnet'=>"2754377", 'fechanac'=>"1963-11-14", 'email'=>"eugeniochoque@masteroruro.cf", 'password'=>Hash::make("2754377Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>25,'paterno'=>"CHUMACERO", 'materno'=>"TÉLLEZ", 'nombres'=>"GISELA ", 'licencia'=>"Or-6-008", 'genero'=>"F", 'carnet'=>"3508294", 'fechanac'=>"1975-9-27", 'email'=>"giselachumacero@masteroruro.cf", 'password'=>Hash::make("3508294Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>26,'paterno'=>"COCA", 'materno'=>"SANDOVAL", 'nombres'=>"JHONNY LUIS", 'licencia'=>"Or-6-054", 'genero'=>"M", 'carnet'=>"3504038", 'fechanac'=>"1972-5-27", 'email'=>"jhonnycoca@masteroruro.cf", 'password'=>Hash::make("3504038Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>27,'paterno'=>"CONDORI", 'materno'=>"CASTRO", 'nombres'=>"ALBERTO ", 'licencia'=>"Or-6-034", 'genero'=>"M", 'carnet'=>"606999", 'fechanac'=>"1950-6-28", 'email'=>"albertocondori@masteroruro.cf", 'password'=>Hash::make("606999Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>28,'paterno'=>"DELGADO", 'materno'=>"ATAHUICHI", 'nombres'=>"CARMEN ANTONIA", 'licencia'=>"Or-6-009", 'genero'=>"F", 'carnet'=>"4291733", 'fechanac'=>"1971-7-17", 'email'=>"carmendelgado@masteroruro.cf", 'password'=>Hash::make("4291733Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>29,'paterno'=>"DURÁN", 'materno'=>"RAMIREZ", 'nombres'=>"CARMEN DRISLEY", 'licencia'=>"Or-6-049", 'genero'=>"F", 'carnet'=>"3537271", 'fechanac'=>"1977-6-4", 'email'=>"carmenduran@masteroruro.cf", 'password'=>Hash::make("3537271Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>30,'paterno'=>"ESCOBAR", 'materno'=>"BARRERA", 'nombres'=>"CARMEN BEATRIZ", 'licencia'=>"Or-6-058", 'genero'=>"F", 'carnet'=>"3089283", 'fechanac'=>"1964-5-17", 'email'=>"carmenescobar@masteroruro.cf", 'password'=>Hash::make("3089283Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>31,'paterno'=>"ESCOBAR", 'materno'=>"BARRERA", 'nombres'=>"MIRIAN SUSY", 'licencia'=>"Or-6-063", 'genero'=>"F", 'carnet'=>"3061400", 'fechanac'=>"1962-12-24", 'email'=>"mirianescobar@masteroruro.cf", 'password'=>Hash::make("3061400Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>32,'paterno'=>"FELICIANO", 'materno'=>"CHOQUE", 'nombres'=>"HILARIÓN RAÚL", 'licencia'=>"Or-6-047", 'genero'=>"M", 'carnet'=>"3548045", 'fechanac'=>"1975-10-21", 'email'=>"hilarionfeliciano@masteroruro.cf", 'password'=>Hash::make("3548045Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>33,'paterno'=>"FLORES", 'materno'=>"FLORES", 'nombres'=>"WILSON GALO", 'licencia'=>"Or-6-010", 'genero'=>"M", 'carnet'=>"5776286", 'fechanac'=>"1988-10-16", 'email'=>"wilsonflores@masteroruro.cf", 'password'=>Hash::make("5776286Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>34,'paterno'=>"GUTIÉRREZ", 'materno'=>"AREQUIPA", 'nombres'=>"GREGORIO ", 'licencia'=>"Or-6-029", 'genero'=>"M", 'carnet'=>"675808", 'fechanac'=>"1955-11-28", 'email'=>"gregoriogutierrez@masteroruro.cf", 'password'=>Hash::make("675808Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>35,'paterno'=>"GUTIÉRREZ", 'materno'=>"CHOQUE", 'nombres'=>"ERICK MARCELO", 'licencia'=>"Or-6-057", 'genero'=>"M", 'carnet'=>"3546830", 'fechanac'=>"1977-12-30", 'email'=>"erickgutierrez@masteroruro.cf", 'password'=>Hash::make("3546830Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>36,'paterno'=>"GUTIÉRREZ", 'materno'=>"LÓPEZ", 'nombres'=>"MARIO ", 'licencia'=>"Or-6-068", 'genero'=>"M", 'carnet'=>"5744984", 'fechanac'=>"1976-3-20", 'email'=>"mariogutierrez@masteroruro.cf", 'password'=>Hash::make("5744984Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>37,'paterno'=>"GUZMAN", 'materno'=>"SANTOS", 'nombres'=>"ALEX ", 'licencia'=>"Or-6-053", 'genero'=>"M", 'carnet'=>"4060486", 'fechanac'=>"1981-11-23", 'email'=>"alexguzman@masteroruro.cf", 'password'=>Hash::make("4060486Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>38,'paterno'=>"HINOJOSA", 'materno'=>"URQUIDI", 'nombres'=>"AMANDA ", 'licencia'=>"Or-6-011", 'genero'=>"F", 'carnet'=>"5761276", 'fechanac'=>"1983-8-1", 'email'=>"amandahinojosa@masteroruro.cf", 'password'=>Hash::make("5761276Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>39,'paterno'=>"HUARACHI", 'materno'=>"", 'nombres'=>"JUAN CARLOS", 'licencia'=>"------", 'genero'=>"M", 'carnet'=>"3522285", 'fechanac'=>"1977-5-30", 'email'=>"juanhuarachi@masteroruro.cf", 'password'=>Hash::make("3522285Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>40,'paterno'=>"HUARIN", 'materno'=>"CANAVIRI", 'nombres'=>"NICOLAS HERBERT", 'licencia'=>"Or-6-012", 'genero'=>"M", 'carnet'=>"3077721", 'fechanac'=>"1966-8-31", 'email'=>"nicolashuarin@masteroruro.cf", 'password'=>Hash::make("3077721Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>41,'paterno'=>"JAVIER", 'materno'=>"SEJAS", 'nombres'=>"SIRLEY TERESA", 'licencia'=>"Or-6-031", 'genero'=>"F", 'carnet'=>"4051860", 'fechanac'=>"1981-10-6", 'email'=>"sirleyjavier@masteroruro.cf", 'password'=>Hash::make("4051860Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>42,'paterno'=>"LARA", 'materno'=>"VALDIVIA", 'nombres'=>"ALVARO RODRIGO", 'licencia'=>"Or-6-013", 'genero'=>"M", 'carnet'=>"3533960", 'fechanac'=>"1979-10-31", 'email'=>"alvarolara@masteroruro.cf", 'password'=>Hash::make("3533960Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>43,'paterno'=>"MAGNE", 'materno'=>"GARNICA", 'nombres'=>"EVELYN SARINA", 'licencia'=>"Or-6-055", 'genero'=>"F", 'carnet'=>"3533395", 'fechanac'=>"1973-11-28", 'email'=>"evelynmagne@masteroruro.cf", 'password'=>Hash::make("3533395Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>44,'paterno'=>"MAGNE", 'materno'=>"PACO", 'nombres'=>"JUAN ", 'licencia'=>"Or-6-025", 'genero'=>"M", 'carnet'=>"585299", 'fechanac'=>"1944-11-24", 'email'=>"juanmagne@masteroruro.cf", 'password'=>Hash::make("585299Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>45,'paterno'=>"MAMANI", 'materno'=>"ACAPA", 'nombres'=>"JANNETH MARIBEL", 'licencia'=>"Or-6-014", 'genero'=>"F", 'carnet'=>"3547544", 'fechanac'=>"1977-5-1", 'email'=>"jannethmamani@masteroruro.cf", 'password'=>Hash::make("3547544Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>46,'paterno'=>"MAMANI", 'materno'=>"ARCE", 'nombres'=>"MARTÍN ", 'licencia'=>"Or-6-027", 'genero'=>"M", 'carnet'=>"1057241", 'fechanac'=>"1955-6-27", 'email'=>"martinmamani@masteroruro.cf", 'password'=>Hash::make("1057241Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>47,'paterno'=>"MAMANI", 'materno'=>"ZAMBRANA", 'nombres'=>"LESLY SARA", 'licencia'=>"Or-6-048", 'genero'=>"F", 'carnet'=>"3556379", 'fechanac'=>"1975-5-8", 'email'=>"leslymamani@masteroruro.cf", 'password'=>Hash::make("3556379Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>48,'paterno'=>"MORANDO", 'materno'=>"GUZMÁN", 'nombres'=>"MAYRA ", 'licencia'=>"Or-6-070", 'genero'=>"F", 'carnet'=>"4078910", 'fechanac'=>"1987-11-13", 'email'=>"mayramorando@masteroruro.cf", 'password'=>Hash::make("4078910Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>49,'paterno'=>"MORANDO", 'materno'=>"GUZMÁN", 'nombres'=>"PAMELA MORAMAY", 'licencia'=>"Or-6-015", 'genero'=>"F", 'carnet'=>"4078911", 'fechanac'=>"1985-7-15", 'email'=>"pamelamorando@masteroruro.cf", 'password'=>Hash::make("4078911Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>50,'paterno'=>"MOREJÓN", 'materno'=>"ECHEVERRÍA", 'nombres'=>"SILVIA ROXANA", 'licencia'=>"Or-6-016", 'genero'=>"F", 'carnet'=>"3548217", 'fechanac'=>"1979-1-9", 'email'=>"silviamorejon@masteroruro.cf", 'password'=>Hash::make("3548217Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>51,'paterno'=>"OCHOA", 'materno'=>"MIRANDA", 'nombres'=>"FREDDY ", 'licencia'=>"Or-6-017", 'genero'=>"M", 'carnet'=>"5066251", 'fechanac'=>"1981-8-11", 'email'=>"freddyochoa@masteroruro.cf", 'password'=>Hash::make("5066251Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>52,'paterno'=>"PÉREZ", 'materno'=>"SALGUEIRO", 'nombres'=>"ENRIQUE ", 'licencia'=>"Or-6-018", 'genero'=>"M", 'carnet'=>"6071240", 'fechanac'=>"1947-8-29", 'email'=>"enriqueperez@masteroruro.cf", 'password'=>Hash::make("6071240Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>53,'paterno'=>"PIZARRO", 'materno'=>"GARISTO", 'nombres'=>"ZENÓN ", 'licencia'=>"Or-6-067", 'genero'=>"M", 'carnet'=>"3098255", 'fechanac'=>"1977-3-24", 'email'=>"zenonpizarro@masteroruro.cf", 'password'=>Hash::make("3098255Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>54,'paterno'=>"POMA", 'materno'=>"CÁCERES", 'nombres'=>"JUVENAL ", 'licencia'=>"Or-6-030", 'genero'=>"M", 'carnet'=>"3541484", 'fechanac'=>"1966-5-4", 'email'=>"juvenalpoma@masteroruro.cf", 'password'=>Hash::make("3541484Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>55,'paterno'=>"RAMOS", 'materno'=>"ESPINOZA", 'nombres'=>"CHRISTIAN CELSO", 'licencia'=>"Or-6-059", 'genero'=>"M", 'carnet'=>"3109142", 'fechanac'=>"1969-7-28", 'email'=>"christianramos@masteroruro.cf", 'password'=>Hash::make("3109142Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>56,'paterno'=>"RAMOS", 'materno'=>"FLORES", 'nombres'=>"ORLANDO ", 'licencia'=>"Or-6-039", 'genero'=>"M", 'carnet'=>"4022044", 'fechanac'=>"1979-1-5", 'email'=>"orlandoramos@masteroruro.cf", 'password'=>Hash::make("4022044Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>57,'paterno'=>"RAMOS", 'materno'=>"MENAR", 'nombres'=>"BRAULIO ", 'licencia'=>"Or-6-019", 'genero'=>"M", 'carnet'=>"3094248", 'fechanac'=>"1972-4-23", 'email'=>"braulioramos@masteroruro.cf", 'password'=>Hash::make("3094248Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>58,'paterno'=>"RODRÍGUEZ", 'materno'=>"CABRERA", 'nombres'=>"ROBERTO FAVIO", 'licencia'=>"Or-6-020", 'genero'=>"M", 'carnet'=>"3556875", 'fechanac'=>"1979-1-23", 'email'=>"robertorodriguez@masteroruro.cf", 'password'=>Hash::make("3556875Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>59,'paterno'=>"ROSSO", 'materno'=>"GUZMÁN", 'nombres'=>"RÓMULO MARCELO", 'licencia'=>"Or-6-026", 'genero'=>"M", 'carnet'=>"3058669", 'fechanac'=>"1961-6-2", 'email'=>"romulorosso@masteroruro.cf", 'password'=>Hash::make("3058669Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>60,'paterno'=>"RUIZ", 'materno'=>"ORELLANA", 'nombres'=>"MIGUEL ALEJANDRO", 'licencia'=>"Or-6-021", 'genero'=>"M", 'carnet'=>"3624395", 'fechanac'=>"1973-6-19", 'email'=>"miguelruiz@masteroruro.cf", 'password'=>Hash::make("3624395Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>61,'paterno'=>"SANCHEZ", 'materno'=>"CALIZAYA", 'nombres'=>"MARÍA SOLEDAD", 'licencia'=>"Or-6-052", 'genero'=>"F", 'carnet'=>"5736046", 'fechanac'=>"1985-10-11", 'email'=>"mariasanchez@masteroruro.cf", 'password'=>Hash::make("5736046Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>62,'paterno'=>"SIÑANI", 'materno'=>"DIAZ", 'nombres'=>"WILFREDO ", 'licencia'=>"Or-6-056", 'genero'=>"M", 'carnet'=>"3557394", 'fechanac'=>"1980-9-2", 'email'=>"wilfredosinani@masteroruro.cf", 'password'=>Hash::make("3557394Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>63,'paterno'=>"SORIA", 'materno'=>"VALLEJOS", 'nombres'=>"JANNETH NORAH", 'licencia'=>"Or-6-022", 'genero'=>"F", 'carnet'=>"3114996", 'fechanac'=>"1969-8-23", 'email'=>"jannethsoria@masteroruro.cf", 'password'=>Hash::make("3114996Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>64,'paterno'=>"SORIA", 'materno'=>"ZURITA", 'nombres'=>"MARIBEL MARCELA", 'licencia'=>"Or-6-028", 'genero'=>"F", 'carnet'=>"3794780", 'fechanac'=>"1973-10-22", 'email'=>"maribelsoria@masteroruro.cf", 'password'=>Hash::make("3794780Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>65,'paterno'=>"TAPIA", 'materno'=>"", 'nombres'=>"CARMEN LITA", 'licencia'=>"Or-6-044", 'genero'=>"F", 'carnet'=>"3516593", 'fechanac'=>"1976-9-28", 'email'=>"carmentapia@masteroruro.cf", 'password'=>Hash::make("3516593Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>66,'paterno'=>"TELLEZ", 'materno'=>"BASCOPÉ", 'nombres'=>"CRISTHIAN ORLANDO", 'licencia'=>"Or-6-050", 'genero'=>"M", 'carnet'=>"6217023", 'fechanac'=>"1983-5-6", 'email'=>"cristhiantellez@masteroruro.cf", 'password'=>Hash::make("6217023Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>67,'paterno'=>"TORREZ", 'materno'=>"FLORES", 'nombres'=>"YOLANDA ", 'licencia'=>"Or-6-035", 'genero'=>"F", 'carnet'=>"3057091", 'fechanac'=>"1963-12-21", 'email'=>"yolandatorrez@masteroruro.cf", 'password'=>Hash::make("3057091Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>68,'paterno'=>"TOTORA", 'materno'=>"", 'nombres'=>"ENRIQUE ", 'licencia'=>"Or-6-024", 'genero'=>"M", 'carnet'=>"3103716", 'fechanac'=>"1965-7-15", 'email'=>"enriquetotora@masteroruro.cf", 'password'=>Hash::make("3103716Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>69,'paterno'=>"UREÑA", 'materno'=>"MERIDA", 'nombres'=>"GREGORIO FERNANDO", 'licencia'=>"Or-6-051", 'genero'=>"M", 'carnet'=>"3395650", 'fechanac'=>"1972-3-12", 'email'=>"gregoriourena@masteroruro.cf", 'password'=>Hash::make("3395650Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>70,'paterno'=>"UYENO", 'materno'=>"MENDIETA", 'nombres'=>"ÁNGEL JULIÁN", 'licencia'=>"Or-6-023", 'genero'=>"M", 'carnet'=>"4193695", 'fechanac'=>"1980-11-20", 'email'=>"angeluyeno@masteroruro.cf", 'password'=>Hash::make("4193695Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>71,'paterno'=>"VACA", 'materno'=>"RAMOS", 'nombres'=>"VLADIMIR CARLOS", 'licencia'=>"------", 'genero'=>"M", 'carnet'=>"", 'fechanac'=>"1984-7-22", 'email'=>"vladimirvaca@masteroruro.cf", 'password'=>Hash::make("Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>72,'paterno'=>"VALLEJOS", 'materno'=>"PANIAGUA", 'nombres'=>"JUAN CARLOS", 'licencia'=>"Or-6-040", 'genero'=>"M", 'carnet'=>"3528103", 'fechanac'=>"1977-5-16", 'email'=>"juanvallejos@masteroruro.cf", 'password'=>Hash::make("3528103Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>73,'paterno'=>"VEIZAN", 'materno'=>"BLACUTH", 'nombres'=>"OLIVIA JUANA", 'licencia'=>"Or-6-045", 'genero'=>"F", 'carnet'=>"3114496", 'fechanac'=>"1967-12-21", 'email'=>"oliviaveizan@masteroruro.cf", 'password'=>Hash::make("3114496Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>74,'paterno'=>"VILLAROEL", 'materno'=>"VIDAURRE", 'nombres'=>"RENÉ ", 'licencia'=>"Or-6-064", 'genero'=>"M", 'carnet'=>"582440", 'fechanac'=>"1947-9-7", 'email'=>"renevillaroel@masteroruro.cf", 'password'=>Hash::make("582440Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>75,'paterno'=>"ZENTENO", 'materno'=>"GUTIÉRREZ", 'nombres'=>"VICTORIA ", 'licencia'=>"------", 'genero'=>"F", 'carnet'=>"5740817", 'fechanac'=>"1985-12-23", 'email'=>"victoriazenteno@masteroruro.cf", 'password'=>Hash::make("5740817Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>76,'paterno'=>"CHAMBI", 'materno'=>"AJATA", 'nombres'=>"ADIMER PAUL", 'licencia'=>"------", 'genero'=>"M", 'carnet'=>"7336199", 'fechanac'=>"1989-04-02", 'email'=>"adimer@masteroruro.cf", 'password'=>Hash::make("7336199Master"),"tipo"=>"COMPETIDOR"],
            ["id"=>77,'paterno'=>"NINO", 'materno'=>"NINO", 'nombres'=>"NINO", 'licencia'=>"------", 'genero'=>"M", 'carnet'=>"7336199", 'fechanac'=>"2010-04-02", 'email'=>"nino@masteroruro.cf", 'password'=>Hash::make("nino"),"tipo"=>"COMPETIDOR"],
            ["id"=>78,'paterno'=>"NINO2", 'materno'=>"NINO2", 'nombres'=>"NINO2", 'licencia'=>"------", 'genero'=>"M", 'carnet'=>"7336199", 'fechanac'=>"2010-04-02", 'email'=>"nino2@masteroruro.cf", 'password'=>Hash::make("nino"),"tipo"=>"COMPETIDOR"],
        ]);
    }
}
